# Harbor Notifier Configuration
# This file contains example configurations for various notification targets

# Server Configuration
server:
  addr: ":8080"
  base_path: "/"
  read_header_timeout: "5s"
  shutdown_timeout: "30s"
  hmac_secret: "your-secret-hmac-key"
  ip_allowlist: []
  enable_pprof: false
  max_request_size: 1048576
  rate_limit: 100
  rate_limit_burst: 10

# Harbor Configuration
harbor:
  base_url: "https://harbor.example.com"
  username: "admin"
  password: "Harbor12345"
  insecure_skip_verify: false
  timeout: "30s"

# Notification Configuration
notify:
  # Telegram Configuration
  telegram:
    enabled: false
    bot_token: "your-telegram-bot-token"
    chat_id: "your-chat-id"
    timeout: "5s"
    rate_per_minute: 20
    debug: false
    webhook:
      enabled: false
      url: "https://your-domain.com/telegram/webhook"
      secret_token: "your-webhook-secret"
      max_connections: 10
      allowed_updates: []
    message_format:
      escape_markdown: true
      disable_web_preview: false
      enable_html: true
      show_timestamp: true
      include_severity: true
      max_message_length: 4096
      custom_prefix: "🚨 [HARBOR]"
      custom_suffix: ""
      severity_colors:
        critical: "🔴"
        high: "🟠"
        medium: "🟡"
        low: "🟢"
        unknown: "⚪"
    templates:
      enabled: true
      path: "/etc/notifier/templates"

  # Email Configuration
  email:
    enabled: false
    subject_prefix: "[Harbor Alert]"
    smtp:
      host: "smtp.gmail.com"
      port: 587
      username: "your_email@gmail.com"
      password: "your_app_password"
      from: "your_email@gmail.com"
      starttls: true
      timeout: "30s"
      auth_type: "xoauth2"
      encryption: "tls"
    to:
      - "admin@example.com"
      - "security@example.com"
      - "devops@example.com"

  # Slack Configuration
  slack:
    enabled: false
    token: "xoxb-your-slack-bot-token"
    channel: "#security-alerts"
    timeout: "5s"
    rate_per_minute: 60
    debug: true
    username: "Harbor Security Bot"
    icon_emoji: ":shield:"
    icon_url: ""
    link_names: true
    unfurl_links: true
    unfurl_media: true
    markdown: true
    message_format:
      escape_markdown: false
      disable_web_preview: false
      enable_html: true
      show_timestamp: true
      include_severity: true
      max_message_length: 3000
      custom_prefix: "🚨 [SECURITY]"
      custom_suffix: "Please review immediately"
      severity_colors:
        critical: "🔴"
        high: "🟠"
        medium: "🟡"
        low: "🟢"
        unknown: "⚪"

  # Mattermost Configuration
  mattermost:
    enabled: false
    server_url: "https://your-mattermost-server.com"
    token: "your-mattermost-bot-token"
    channel: "security-alerts"
    team: "your-team-name"
    timeout: "5s"
    rate_per_minute: 60
    debug: true
    username: "Harbor Security Bot"
    icon_emoji: ":shield:"
    icon_url: ""
    unfurl_links: true
    unfurl_media: true
    markdown: true
    create_channel: false
    channel_type: "public"
    message_format:
      escape_markdown: false
      disable_web_preview: false
      enable_html: true
      show_timestamp: true
      include_severity: true
      max_message_length: 3000
      custom_prefix: "🚨 [SECURITY]"
      custom_suffix: "Please review immediately"
      severity_colors:
        critical: "🔴"
        high: "🟠"
        medium: "🟡"
        low: "🟢"
        unknown: "⚪"
    webhook:
      enabled: false
      url: "https://your-mattermost-server.com/hooks/your-webhook-url"
      secret_token: "your-webhook-secret"
      max_connections: 10
      allowed_updates: []

# Processing Configuration
processing:
  enrich_via_harbor_api: true
  max_concurrency: 8
  max_queue: 1024
  retry:
    max_attempts: 8
    initial_backoff: "1s"
    max_backoff: "2m"

# Observability Configuration
observability:
  metrics_addr: ":9090"
  log:
    level: "info"
    format: "json"

# Templates Configuration
templates:
  enabled: true
  path: "/etc/notifier/templates"

---

# Example: Gmail Configuration
notify:
  email:
    enabled: true
    subject_prefix: "[Gmail Alert]"
    smtp:
      host: "smtp.gmail.com"
      port: 587
      username: "your_email@gmail.com"
      password: "your_app_password"
      from: "your_email@gmail.com"
      starttls: true
      timeout: "30s"
      auth_type: "xoauth2"
      encryption: "tls"
    to:
      - "team@example.com"

---

# Example: Slack Configuration
notify:
  slack:
    enabled: true
    token: "xoxb-your-slack-bot-token"
    channel: "#security-alerts"
    timeout: "5s"
    rate_per_minute: 60
    debug: true
    username: "Harbor Security Bot"
    icon_emoji: ":shield:"
    link_names: true
    unfurl_links: true
    unfurl_media: true
    markdown: true
    message_format:
      escape_markdown: false
      disable_web_preview: false
      enable_html: true
      show_timestamp: true
      include_severity: true
      max_message_length: 3000
      custom_prefix: "🚨 [SECURITY]"
      custom_suffix: "Please review immediately"
      severity_colors:
        critical: "🔴"
        high: "🟠"
        medium: "🟡"
        low: "🟢"
        unknown: "⚪"

---

# Example: Mattermost Configuration
notify:
  mattermost:
    enabled: true
    server_url: "https://your-mattermost-server.com"
    token: "your-mattermost-bot-token"
    channel: "security-alerts"
    team: "your-team-name"
    timeout: "5s"
    rate_per_minute: 60
    debug: true
    username: "Harbor Security Bot"
    icon_emoji: ":shield:"
    icon_url: ""
    unfurl_links: true
    unfurl_media: true
    markdown: true
    create_channel: false
    channel_type: "public"
    message_format:
      escape_markdown: false
      disable_web_preview: false
      enable_html: true
      show_timestamp: true
      include_severity: true
      max_message_length: 3000
      custom_prefix: "🚨 [SECURITY]"
      custom_suffix: "Please review immediately"
      severity_colors:
        critical: "🔴"
        high: "🟠"
        medium: "🟡"
        low: "🟢"
        unknown: "⚪"
    webhook:
      enabled: false
      url: "https://your-mattermost-server.com/hooks/your-webhook-url"
      secret_token: "your-webhook-secret"
      max_connections: 10
      allowed_updates: []