global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'ht-notifier'
    static_configs:
      - targets: ['ht-notifier:9090']
    metrics_path: /metrics
    scrape_interval: 15s
    scrape_timeout: 10s

  - job_name: 'harbor'
    static_configs:
      - targets: ['harbor:80']
    metrics_path: /api/v2.0/metrics
    scrape_interval: 30s
    scrape_timeout: 10s

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    metrics_path: /api/metrics
    scrape_interval: 30s
    scrape_timeout: 10s